-- AUTH_KEY definition

CREATE TABLE "AUTH_KEY" 
   (	"KEY_NO" NUMBER, 
	"EMAIL" NVARCHAR2(50) NOT NULL ENABLE, 
	"AUTH_KEY" CHAR(6) NOT NULL ENABLE, 
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 PRIMARY KEY ("KEY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SYS_C008696" ON "AUTH_KEY" ("KEY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN AUTH_KEY.KEY_NO IS '인증키 구분 번호(시퀀스)';
COMMENT ON COLUMN AUTH_KEY.EMAIL IS '인증 이메일';
COMMENT ON COLUMN AUTH_KEY.AUTH_KEY IS '인증 번호';
COMMENT ON COLUMN AUTH_KEY.CREATE_TIME IS '인증 번호 생성 시간';


-- BOARD_TYPE definition

CREATE TABLE "BOARD_TYPE" 
   (	"BOARD_CODE" NUMBER NOT NULL ENABLE, 
	"BOARD_NAME" NVARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY ("BOARD_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_BOARD_TYPE" ON "BOARD_TYPE" ("BOARD_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN BOARD_TYPE.BOARD_CODE IS '게시판 코드 번호(PK)';
COMMENT ON COLUMN BOARD_TYPE.BOARD_NAME IS '게시판 명';


-- "MEMBER" definition

CREATE TABLE "MEMBER" 
   (	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"MEMBER_EMAIL" NVARCHAR2(50) NOT NULL ENABLE, 
	"MEMBER_PW" NVARCHAR2(100) NOT NULL ENABLE, 
	"MEMBER_NICKNAME" NVARCHAR2(10) NOT NULL ENABLE, 
	"MEMBER_TEL" CHAR(11) NOT NULL ENABLE, 
	"MEMBER_ADDRESS" NVARCHAR2(300), 
	"PROFILE_IMG" VARCHAR2(300), 
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MEMBER_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"AUTHORITY" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_MEMBER" ON "MEMBER" ("MEMBER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원번호(PK)';
COMMENT ON COLUMN "MEMBER".MEMBER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER".MEMBER_NICKNAME IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER".MEMBER_TEL IS '회원 전화번호';
COMMENT ON COLUMN "MEMBER".MEMBER_ADDRESS IS '회원 주소';
COMMENT ON COLUMN "MEMBER".PROFILE_IMG IS '프로필 이미지';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".MEMBER_DEL_FL IS '탈퇴여부(Y, N)';
COMMENT ON COLUMN "MEMBER".AUTHORITY IS '회원 권한(관리자 Y)';


-- CATEGORY definition

CREATE TABLE "CATEGORY" 
   (	"CATEGORY_NO" NUMBER NOT NULL ENABLE, 
	"BOARD_CODE" NUMBER NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(20), 
	 CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("CATEGORY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "CATEGORY" ADD CONSTRAINT "FK_BOARD_TYPE_TO_CATEGORY_1" FOREIGN KEY ("BOARD_CODE")
	  REFERENCES "BOARD_TYPE" ("BOARD_CODE") ENABLE;

CREATE UNIQUE INDEX "PK_CATEGORY" ON "CATEGORY" ("CATEGORY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '게시판 카테고리(PK)';
COMMENT ON COLUMN CATEGORY.BOARD_CODE IS '게시판 코드 번호(PK)';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '게시판 카테고리 이름';


-- BOARD definition

CREATE TABLE "BOARD" 
   (	"BOARD_NO" NUMBER NOT NULL ENABLE, 
	"BOARD_TITLE" NVARCHAR2(100) NOT NULL ENABLE, 
	"BOARD_CONTENT" VARCHAR2(4000) NOT NULL ENABLE, 
	"BOARD_WRITE_DATE" DATE NOT NULL ENABLE, 
	"BOARD_UPDATE_DATE" DATE, 
	"READ_COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"BOARD_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"BOARD_CODE" NUMBER NOT NULL ENABLE, 
	"CATEGORY_NO" NUMBER, 
	 CONSTRAINT "PK_BOARD" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "BOARD_DEL_CHECK" CHECK ("BOARD_DEL_FL" IN ('Y', 'N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY ("BOARD_CODE")
	  REFERENCES "BOARD_TYPE" ("BOARD_CODE") ENABLE;
  ALTER TABLE "BOARD" ADD CONSTRAINT "FK_CATEGORY_TO_BOARD_1" FOREIGN KEY ("CATEGORY_NO")
	  REFERENCES "CATEGORY" ("CATEGORY_NO") ENABLE;

CREATE UNIQUE INDEX "PK_BOARD" ON "BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호(PK)';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.BOARD_WRITE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.BOARD_UPDATE_DATE IS '게시글 마지막 수정일';
COMMENT ON COLUMN BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_DEL_FL IS '게시글 삭제여부( Y, N)';
COMMENT ON COLUMN BOARD.MEMBER_NO IS '회원번호(PK)';
COMMENT ON COLUMN BOARD.BOARD_CODE IS '게시판 코드 번호(PK)';


-- BOARD_IMG definition

CREATE TABLE "BOARD_IMG" 
   (	"IMG_NO" NUMBER NOT NULL ENABLE, 
	"IMG_PATH" VARCHAR2(200) NOT NULL ENABLE, 
	"IMG_ORIGINAL_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"IMG_RENAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"IMG_ORDER" NUMBER, 
	"BOARD_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY ("IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "BOARD" ("BOARD_NO") ENABLE;

CREATE UNIQUE INDEX "PK_BOARD_IMG" ON "BOARD_IMG" ("IMG_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN BOARD_IMG.IMG_NO IS '이미지번호(PK)';
COMMENT ON COLUMN BOARD_IMG.IMG_PATH IS '이미지 요청 경로';
COMMENT ON COLUMN BOARD_IMG.IMG_ORIGINAL_NAME IS '이미지 원본명';
COMMENT ON COLUMN BOARD_IMG.IMG_RENAME IS '이미지 변경명';
COMMENT ON COLUMN BOARD_IMG.IMG_ORDER IS '이미지 순서';
COMMENT ON COLUMN BOARD_IMG.BOARD_NO IS '게시글 번호(PK)';


-- BOARD_LIKE definition

CREATE TABLE "BOARD_LIKE" 
   (	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"BOARD_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_BOARD_LIKE" PRIMARY KEY ("MEMBER_NO", "BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_LIKE_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;
  ALTER TABLE "BOARD_LIKE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_LIKE_1" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "BOARD" ("BOARD_NO") ENABLE;

CREATE UNIQUE INDEX "PK_BOARD_LIKE" ON "BOARD_LIKE" ("MEMBER_NO", "BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN BOARD_LIKE.MEMBER_NO IS '회원번호(PK)';
COMMENT ON COLUMN BOARD_LIKE.BOARD_NO IS '게시글 번호(PK)';


-- "COMMENT" definition

CREATE TABLE "COMMENT" 
   (	"COMMENT_NO" NUMBER NOT NULL ENABLE, 
	"COMMENT_CONTENT" VARCHAR2(4000) NOT NULL ENABLE, 
	"COMMENT_WRITE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"COMMENT_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"BOARD_NO" NUMBER NOT NULL ENABLE, 
	"PARENT_COMMENT_NO" NUMBER, 
	 CONSTRAINT "PK_COMMENT" PRIMARY KEY ("COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMMENT_DEL_CHECK" CHECK ("COMMENT_DEL_FL" IN ('Y', 'N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_BOARD_TO_COMMENT_1" FOREIGN KEY ("BOARD_NO")
	  REFERENCES "BOARD" ("BOARD_NO") ENABLE;
  ALTER TABLE "COMMENT" ADD CONSTRAINT "FK_COMMENT_TO_COMMENT_1" FOREIGN KEY ("PARENT_COMMENT_NO")
	  REFERENCES "COMMENT" ("COMMENT_NO") ENABLE;

CREATE UNIQUE INDEX "PK_COMMENT" ON "COMMENT" ("COMMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "COMMENT".COMMENT_NO IS '댓글번호(PK)';
COMMENT ON COLUMN "COMMENT".COMMENT_CONTENT IS '댓글 내용';
COMMENT ON COLUMN "COMMENT".COMMENT_WRITE_DATE IS '댓글 작성일';
COMMENT ON COLUMN "COMMENT".COMMENT_DEL_FL IS '댓글 삭제여부 (Y, N)';
COMMENT ON COLUMN "COMMENT".MEMBER_NO IS '회원번호(PK)';
COMMENT ON COLUMN "COMMENT".BOARD_NO IS '게시글 번호(PK)';
COMMENT ON COLUMN "COMMENT".PARENT_COMMENT_NO IS '댓글번호(PK)';