INSERT INTO NOTI_CATEGORY (NOTI_CODE,NOTI_TYPE) VALUES (1,'예약 승인');
INSERT INTO NOTI_CATEGORY (NOTI_CODE,NOTI_TYPE) VALUES (2,'예약 거절');
INSERT INTO NOTI_CATEGORY (NOTI_CODE,NOTI_TYPE) VALUES (3,'예약 신청');
INSERT INTO NOTI_CATEGORY (NOTI_CODE,NOTI_TYPE) VALUES (4,'예약 취소');
INSERT INTO NOTI_CATEGORY (NOTI_CODE,NOTI_TYPE) VALUES (5,'리뷰');
INSERT INTO NOTI_CATEGORY (NOTI_CODE,NOTI_TYPE) VALUES (6,'리뷰 신고');
INSERT INTO NOTI_CATEGORY (NOTI_CODE,NOTI_TYPE) VALUES (7,'가게 신고');
