INSERT INTO REQUEST_CATEGORY (REQUEST_CATEGORY_CODE,REQUEST_CATEGORY_TITLE) VALUES (1,'가게 폐업');
INSERT INTO REQUEST_CATEGORY (REQUEST_CATEGORY_CODE,REQUEST_CATEGORY_TITLE) VALUES (2,'가게 메뉴 수정');
INSERT INTO REQUEST_CATEGORY (REQUEST_CATEGORY_CODE,REQUEST_CATEGORY_TITLE) VALUES (6,'가게 기본 정보 수정');
INSERT INTO REQUEST_CATEGORY (REQUEST_CATEGORY_CODE,REQUEST_CATEGORY_TITLE) VALUES (7,'가게 영업 시간 수정');
