-- AUTH_KEY definition

CREATE TABLE "AUTH_KEY" 
   (	"KEY_NO" NUMBER NOT NULL ENABLE, 
	"TEL_NUMBER" NVARCHAR2(11) NOT NULL ENABLE, 
	"AUTH_KEY" NVARCHAR2(6) NOT NULL ENABLE, 
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY ("KEY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_AUTH_KEY" ON "AUTH_KEY" ("KEY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN AUTH_KEY.KEY_NO IS '인증키 구분 번호 (시퀀스 생성)';
COMMENT ON COLUMN AUTH_KEY.TEL_NUMBER IS '인증 전화번호';
COMMENT ON COLUMN AUTH_KEY.AUTH_KEY IS '인증번호';
COMMENT ON COLUMN AUTH_KEY.CREATE_TIME IS '인증 번호 생성 시간';


-- CATEGORY definition

CREATE TABLE "CATEGORY" 
   (	"CATEGORY_CODE" NUMBER NOT NULL ENABLE, 
	"CATEGORY_TITLE" NVARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("CATEGORY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_CATEGORY" ON "CATEGORY" ("CATEGORY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN CATEGORY.CATEGORY_CODE IS '카테고리 코드 (PK)';
COMMENT ON COLUMN CATEGORY.CATEGORY_TITLE IS '카테고리 이름';


-- CHATTING_ROOM definition

CREATE TABLE "CHATTING_ROOM" 
   (	"CHATTING_NO" NUMBER NOT NULL ENABLE, 
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"OPEN_MEMBER" NUMBER NOT NULL ENABLE, 
	"PARTICIPANT" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_CHATTING_ROOM" PRIMARY KEY ("CHATTING_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_CHATTING_ROOM" ON "CHATTING_ROOM" ("CHATTING_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN CHATTING_ROOM.CHATTING_NO IS '채팅방';
COMMENT ON COLUMN CHATTING_ROOM.CREATE_DATE IS '채팅방';
COMMENT ON COLUMN CHATTING_ROOM.OPEN_MEMBER IS '개설자';
COMMENT ON COLUMN CHATTING_ROOM.PARTICIPANT IS '참여자';


-- HASH definition

CREATE TABLE "HASH" 
   (	"HASH_NO" NUMBER NOT NULL ENABLE, 
	"HASH_TITLE" NVARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_HASH" PRIMARY KEY ("HASH_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_HASH" ON "HASH" ("HASH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN HASH.HASH_NO IS '해시태그 번호 (PK)';
COMMENT ON COLUMN HASH.HASH_TITLE IS '해시태그 내용';


-- "MEMBER" definition

CREATE TABLE "MEMBER" 
   (	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"MEMBER_CODE" CHAR(1) DEFAULT 1 NOT NULL ENABLE, 
	"MEMBER_ID" NVARCHAR2(20) NOT NULL ENABLE, 
	"MEMBER_EMAIL" NVARCHAR2(50) NOT NULL ENABLE, 
	"MEMBER_NAME" NVARCHAR2(15) NOT NULL ENABLE, 
	"MEMBER_NICKNAME" NVARCHAR2(20), 
	"MEMBER_PW" NVARCHAR2(100) NOT NULL ENABLE, 
	"MEMBER_TEL" CHAR(11) NOT NULL ENABLE, 
	"PROFILE_IMG" VARCHAR2(300) DEFAULT '/images/user.png', 
	"ENROLL_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MEMBER_STATUS" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MEMBER_FLAG" NUMBER DEFAULT 0, 
	 CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MEMBER_STATUS_CHECK" CHECK ("MEMBER_STATUS" IN('Y','N','W')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_MEMBER" ON "MEMBER" ("MEMBER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "MEMBER".MEMBER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN "MEMBER".MEMBER_CODE IS '일반 회원: 1 / 가게  주인: 2 / 관리자 : 3';
COMMENT ON COLUMN "MEMBER".MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN "MEMBER".MEMBER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN "MEMBER".MEMBER_NAME IS '회원 이름';
COMMENT ON COLUMN "MEMBER".MEMBER_NICKNAME IS '회원 닉네임';
COMMENT ON COLUMN "MEMBER".MEMBER_PW IS '회원 비밀번호(암호화)';
COMMENT ON COLUMN "MEMBER".MEMBER_TEL IS '회원 전화번호';
COMMENT ON COLUMN "MEMBER".PROFILE_IMG IS '프로필 이미지';
COMMENT ON COLUMN "MEMBER".ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN "MEMBER".MEMBER_STATUS IS '회원 탈퇴 여부 ( Y / N / W )';
COMMENT ON COLUMN "MEMBER".MEMBER_FLAG IS '회원 경고 횟수';


-- MESSAGE definition

CREATE TABLE "MESSAGE" 
   (	"MESSAGE_NO" NUMBER NOT NULL ENABLE, 
	"MESSAGE_CONTENT" VARCHAR2(4000) NOT NULL ENABLE, 
	"READ_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"SEND_TIME" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"CHATTING_NO" NUMBER NOT NULL ENABLE, 
	"TARGET_NO" NUMBER, 
	 CONSTRAINT "PK_MESSAGE" PRIMARY KEY ("MESSAGE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "READ_FL_CHECK" CHECK ("READ_FL" IN('Y','N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_MESSAGE" ON "MESSAGE" ("MESSAGE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN MESSAGE.MESSAGE_NO IS '메시지';
COMMENT ON COLUMN MESSAGE.MESSAGE_CONTENT IS '메시지';
COMMENT ON COLUMN MESSAGE.READ_FL IS '읽음';
COMMENT ON COLUMN MESSAGE.SEND_TIME IS '메시지';
COMMENT ON COLUMN MESSAGE.MEMBER_NO IS '보낸 회원';
COMMENT ON COLUMN MESSAGE.CHATTING_NO IS '채팅방';


-- NOTI_CATEGORY definition

CREATE TABLE "NOTI_CATEGORY" 
   (	"NOTI_CODE" NUMBER NOT NULL ENABLE, 
	"NOTI_TYPE" NVARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_NOTI_CATEGORY" PRIMARY KEY ("NOTI_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_NOTI_CATEGORY" ON "NOTI_CATEGORY" ("NOTI_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN NOTI_CATEGORY.NOTI_CODE IS '알림카테고리코드';
COMMENT ON COLUMN NOTI_CATEGORY.NOTI_TYPE IS '알림종류(전체, 신고 ....)';


-- OFF_DAY definition

CREATE TABLE "OFF_DAY" 
   (	"OFF_DAY_NO" NUMBER NOT NULL ENABLE, 
	"OFF_DAY_TITLE" NVARCHAR2(50), 
	"OFF_DAY_START" DATE NOT NULL ENABLE, 
	"OFF_DAY_END" DATE NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DAY_OFF" PRIMARY KEY ("OFF_DAY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_DAY_OFF" ON "OFF_DAY" ("OFF_DAY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN OFF_DAY.OFF_DAY_NO IS '지정 휴무일 번호 (PK)';
COMMENT ON COLUMN OFF_DAY.OFF_DAY_TITLE IS 'title (데이터 객체명)';
COMMENT ON COLUMN OFF_DAY.OFF_DAY_START IS 'start';
COMMENT ON COLUMN OFF_DAY.OFF_DAY_END IS 'end';
COMMENT ON COLUMN OFF_DAY.STORE_NO IS '사업자 등록 번호 (PK)';


-- OFF_WEEK definition

CREATE TABLE "OFF_WEEK" 
   (	"OFF_WEEK_NO" NUMBER NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"OFF_WEEK" CHAR(1) NOT NULL ENABLE, 
	 CONSTRAINT "PK_WEEK_OFF" PRIMARY KEY ("OFF_WEEK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_WEEK_OFF" ON "OFF_WEEK" ("OFF_WEEK_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN OFF_WEEK.OFF_WEEK_NO IS '휴무일 번호 (PK)';
COMMENT ON COLUMN OFF_WEEK.STORE_NO IS '사업자 등록 번호 (PK)';
COMMENT ON COLUMN OFF_WEEK.OFF_WEEK IS '휴무 요일 번호';


-- REQUEST_CATEGORY definition

CREATE TABLE "REQUEST_CATEGORY" 
   (	"REQUEST_CATEGORY_CODE" NUMBER NOT NULL ENABLE, 
	"REQUEST_CATEGORY_TITLE" NVARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_REQUEST_CATEGORY" PRIMARY KEY ("REQUEST_CATEGORY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "PK_REQUEST_CATEGORY" ON "REQUEST_CATEGORY" ("REQUEST_CATEGORY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- NOTIFICATION definition

CREATE TABLE "NOTIFICATION" 
   (	"NOTIFICATION_NO" NUMBER NOT NULL ENABLE, 
	"NOTIFICATION_CONTENT" NVARCHAR2(500) NOT NULL ENABLE, 
	"NOTIFICATION_CHECK" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"NOTIFICATION_DATE" DATE DEFAULT CURRENT_DATE NOT NULL ENABLE, 
	"NOTIFICATION_URL" NVARCHAR2(500), 
	"SEND_MEMBER_PROFILE_IMG" VARCHAR2(300), 
	"SEND_MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"RECEIVE_MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"NOTIFICATION_TYPE" VARCHAR2(1000) NOT NULL ENABLE, 
	"NOTI_CODE" NUMBER, 
	 CONSTRAINT "PK_NOTIFICATION" PRIMARY KEY ("NOTIFICATION_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "NOTIFICATION_CHECK" CHECK ("NOTIFICATION_CHECK" IN('Y','N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_NOTI_CATEGORY_TO_NOTIFICATION_1" FOREIGN KEY ("NOTI_CODE")
	  REFERENCES "NOTI_CATEGORY" ("NOTI_CODE") ENABLE;
  ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_MEMBER_TO_NOTIFICATION_1" FOREIGN KEY ("RECEIVE_MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;

CREATE UNIQUE INDEX "PK_NOTIFICATION" ON "NOTIFICATION" ("NOTIFICATION_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_NO IS '알림 번호';
COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_CONTENT IS '알림 내용';
COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_CHECK IS '알림 확인';
COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_DATE IS '알림 시간';
COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_URL IS '알림 클릭시 이동하는 주소';
COMMENT ON COLUMN NOTIFICATION.SEND_MEMBER_PROFILE_IMG IS '알림 보낸 회원 프로필 이미지';
COMMENT ON COLUMN NOTIFICATION.SEND_MEMBER_NO IS '알림 보낸 회원 번호';
COMMENT ON COLUMN NOTIFICATION.RECEIVE_MEMBER_NO IS '회원 번호 (FK)';
COMMENT ON COLUMN NOTIFICATION.NOTIFICATION_TYPE IS '알림 종류';


-- STORE definition

CREATE TABLE "STORE" 
   (	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"STORE_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	"STORE_INFO" NVARCHAR2(1000), 
	"STORE_LOCATION" NVARCHAR2(300) NOT NULL ENABLE, 
	"STORE_STATUS" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STORE_MAX_NUMBER" NUMBER, 
	"STORE_TEL" CHAR(11) NOT NULL ENABLE, 
	"OPEN_HOUR" NVARCHAR2(20) NOT NULL ENABLE, 
	"CLOSE_HOUR" NVARCHAR2(20) NOT NULL ENABLE, 
	"BREAKTIME_START" NVARCHAR2(20), 
	"BREAKTIME_END" NVARCHAR2(20), 
	"STORE_CLOSED" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"STORE_IMG" NVARCHAR2(300), 
	"TOTAL_RATING" NUMBER NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"STORE_MAX_TABLE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_STORE" PRIMARY KEY ("STORE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "STORE_STATUS_CHECK" CHECK ("STORE_STATUS" IN('Y','N')) ENABLE, 
	 CONSTRAINT "STORE_CLOSED_CHECK" CHECK ("STORE_CLOSED" IN('Y','N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "STORE" ADD CONSTRAINT "FK_MEMBER_TO_STORE_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;

CREATE UNIQUE INDEX "PK_STORE" ON "STORE" ("STORE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN STORE.STORE_NO IS '사업자 등록 번호 (PK)';
COMMENT ON COLUMN STORE.STORE_NAME IS '음식점 이름';
COMMENT ON COLUMN STORE.STORE_INFO IS '음식점 소개';
COMMENT ON COLUMN STORE.STORE_LOCATION IS '음식점 위치';
COMMENT ON COLUMN STORE.STORE_STATUS IS '예약 가능 여부( Y / N )';
COMMENT ON COLUMN STORE.STORE_MAX_NUMBER IS '최대 예약 인원';
COMMENT ON COLUMN STORE.STORE_TEL IS '음식점 전화번호';
COMMENT ON COLUMN STORE.OPEN_HOUR IS '영업 시간';
COMMENT ON COLUMN STORE.CLOSE_HOUR IS '영업 종료 시간';
COMMENT ON COLUMN STORE.BREAKTIME_START IS '브레이크 타임 시작 시간';
COMMENT ON COLUMN STORE.BREAKTIME_END IS '브레이크 타임 종료 시간';
COMMENT ON COLUMN STORE.STORE_CLOSED IS '폐업 여부 ( Y / N )';
COMMENT ON COLUMN STORE.STORE_IMG IS '가게 이미지';
COMMENT ON COLUMN STORE.TOTAL_RATING IS '합산, 계산한 별점';
COMMENT ON COLUMN STORE.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN STORE.STORE_MAX_TABLE IS '쵀대 예약 팀 수(테이블)';


-- STORE_CATEGORY definition

CREATE TABLE "STORE_CATEGORY" 
   (	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"CATEGORY_CODE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_STORE_CATEGORY" PRIMARY KEY ("STORE_NO", "CATEGORY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "STORE_CATEGORY" ADD CONSTRAINT "FK_STORE_TO_STORE_CATEGORY_1" FOREIGN KEY ("STORE_NO")
	  REFERENCES "STORE" ("STORE_NO") ENABLE;
  ALTER TABLE "STORE_CATEGORY" ADD CONSTRAINT "FK_CATEGORY_TO_STORE_CATEGORY_1" FOREIGN KEY ("CATEGORY_CODE")
	  REFERENCES "CATEGORY" ("CATEGORY_CODE") ENABLE;

CREATE UNIQUE INDEX "PK_STORE_CATEGORY" ON "STORE_CATEGORY" ("STORE_NO", "CATEGORY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN STORE_CATEGORY.STORE_NO IS '사업자 등록 번호 (PFK)';
COMMENT ON COLUMN STORE_CATEGORY.CATEGORY_CODE IS '카테고리 코드 (PFK)';


-- BOOKMARK definition

CREATE TABLE "BOOKMARK" 
   (	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BOOKMARK" PRIMARY KEY ("MEMBER_NO", "STORE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_MEMBER_TO_BOOKMARK_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;
  ALTER TABLE "BOOKMARK" ADD CONSTRAINT "FK_STORE_TO_BOOKMARK_1" FOREIGN KEY ("STORE_NO")
	  REFERENCES "STORE" ("STORE_NO") ENABLE;

CREATE UNIQUE INDEX "PK_BOOKMARK" ON "BOOKMARK" ("MEMBER_NO", "STORE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN BOOKMARK.MEMBER_NO IS '회원 번호(PFK)';
COMMENT ON COLUMN BOOKMARK.STORE_NO IS '사업자 등록 번호 (PFK)';


-- MENU definition

CREATE TABLE "MENU" 
   (	"MENU_NO" NUMBER NOT NULL ENABLE, 
	"MENU_TITLE" NVARCHAR2(100) NOT NULL ENABLE, 
	"MENU_AMOUNT" NUMBER NOT NULL ENABLE, 
	"MENU_CONTENT" NVARCHAR2(300), 
	"MENU_IMG_URL" VARCHAR2(300), 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"MENU_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_MENU" PRIMARY KEY ("MENU_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "MENU_FL_CHECK" CHECK ("MENU_FL" IN('Y','N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "MENU" ADD CONSTRAINT "FK_STORE_TO_MENU_1" FOREIGN KEY ("STORE_NO")
	  REFERENCES "STORE" ("STORE_NO") ENABLE;

CREATE UNIQUE INDEX "PK_MENU" ON "MENU" ("MENU_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN MENU.MENU_NO IS '메뉴 번호 (PK)';
COMMENT ON COLUMN MENU.MENU_TITLE IS '메뉴';
COMMENT ON COLUMN MENU.MENU_AMOUNT IS '가격';
COMMENT ON COLUMN MENU.MENU_CONTENT IS '추가 기재 내용';
COMMENT ON COLUMN MENU.MENU_IMG_URL IS '메뉴 이미지';
COMMENT ON COLUMN MENU.STORE_NO IS '사업자 등록 번호 (FK)';
COMMENT ON COLUMN MENU.MENU_FL IS '메뉴 삭제 여부 ( Y / N )';


-- REQUEST_EDIT definition

CREATE TABLE "REQUEST_EDIT" 
   (	"REQUEST_NO" NUMBER NOT NULL ENABLE, 
	"REQUEST_CONTENT" NVARCHAR2(1000) NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"REQUEST_CATEGORY_CODE" NUMBER NOT NULL ENABLE, 
	"REQUEST_DATE" DATE DEFAULT SYSDATE, 
	"REQUEST_DEL_FL" CHAR(1) DEFAULT 'N', 
	 CONSTRAINT "PK_REQUEST_EDIT" PRIMARY KEY ("REQUEST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "REQUEST_EDIT_STATUS_CHECK" CHECK ("REQUEST_DEL_FL" IN('Y','N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "REQUEST_EDIT" ADD CONSTRAINT "FK_STORE_TO_REQUEST_EDIT_1" FOREIGN KEY ("STORE_NO")
	  REFERENCES "STORE" ("STORE_NO") ENABLE;
  ALTER TABLE "REQUEST_EDIT" ADD CONSTRAINT "FK_MEMBER_TO_REQUEST_EDIT_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;
  ALTER TABLE "REQUEST_EDIT" ADD CONSTRAINT "FK_REQUEST_CATEGORY_TO_REQUEST_EDIT_1" FOREIGN KEY ("REQUEST_CATEGORY_CODE")
	  REFERENCES "REQUEST_CATEGORY" ("REQUEST_CATEGORY_CODE") ENABLE;

CREATE UNIQUE INDEX "PK_REQUEST_EDIT" ON "REQUEST_EDIT" ("REQUEST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN REQUEST_EDIT.REQUEST_NO IS '정정 접수 번호 (PK)';
COMMENT ON COLUMN REQUEST_EDIT.REQUEST_CONTENT IS '신고 내용';
COMMENT ON COLUMN REQUEST_EDIT.STORE_NO IS '사업자 등록 번호 (FK)';
COMMENT ON COLUMN REQUEST_EDIT.MEMBER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN REQUEST_EDIT.REQUEST_CATEGORY_CODE IS '신고 카테고리 번호';


-- RESERVATION definition

CREATE TABLE "RESERVATION" 
   (	"RESERV_NO" NUMBER NOT NULL ENABLE, 
	"RESERV_DATE" DATE NOT NULL ENABLE, 
	"RESERV_TIME" NVARCHAR2(20) NOT NULL ENABLE, 
	"RESERV_COUNT" NUMBER NOT NULL ENABLE, 
	"RESERV_STATUS_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"RESERV_REQUEST" NVARCHAR2(2000), 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"VISIT_NAME" NVARCHAR2(15), 
	"VISIT_TEL" CHAR(11), 
	 CONSTRAINT "PK_RESERVATION" PRIMARY KEY ("RESERV_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_MEMBER_TO_RESERVATION_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;
  ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_STORE_TO_RESERVATION_1" FOREIGN KEY ("STORE_NO")
	  REFERENCES "STORE" ("STORE_NO") ENABLE;

CREATE UNIQUE INDEX "PK_RESERVATION" ON "RESERVATION" ("RESERV_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN RESERVATION.RESERV_NO IS '예약 번호 (PK)';
COMMENT ON COLUMN RESERVATION.RESERV_DATE IS '예약 일자';
COMMENT ON COLUMN RESERVATION.RESERV_TIME IS '이용 시간';
COMMENT ON COLUMN RESERVATION.RESERV_COUNT IS '예약 인원';
COMMENT ON COLUMN RESERVATION.RESERV_STATUS_FL IS '예약 상태 ( N: 예약대기 / Y:예약확정 / C: 예약 취소 /  X: 노쇼)';
COMMENT ON COLUMN RESERVATION.RESERV_REQUEST IS '예약 시 요청사항';
COMMENT ON COLUMN RESERVATION.MEMBER_NO IS '회원 번호(FK)';
COMMENT ON COLUMN RESERVATION.STORE_NO IS '사업자 등록 번호 (fK)';


-- REVIEW definition

CREATE TABLE "REVIEW" 
   (	"REVIEW_NO" NUMBER NOT NULL ENABLE, 
	"REVIEW_RATING" NUMBER, 
	"REVIEW_CONTENT" NVARCHAR2(1000), 
	"REVIEW__REG_DATE" DATE NOT NULL ENABLE, 
	"REVIEW_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"RESERV_NO" NUMBER, 
	 CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEW_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CHECK ("REVIEW_DEL_FL" IN('Y','N', 'W')) ENABLE, 
	 CONSTRAINT "REVIEW_DEL_FL_CHECK" CHECK ("REVIEW_DEL_FL" IN ('Y', 'N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_RESERVATION_TO_REVIEW_1" FOREIGN KEY ("RESERV_NO")
	  REFERENCES "RESERVATION" ("RESERV_NO") ENABLE;
  ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;
  ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_STORE_TO_REVIEW_1" FOREIGN KEY ("STORE_NO")
	  REFERENCES "STORE" ("STORE_NO") ENABLE;

CREATE UNIQUE INDEX "PK_REVIEW" ON "REVIEW" ("REVIEW_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN REVIEW.REVIEW_NO IS '후기글 번호 (PK)';
COMMENT ON COLUMN REVIEW.REVIEW_RATING IS '개인이 부여한 별점';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '후기 내용';
COMMENT ON COLUMN REVIEW.REVIEW__REG_DATE IS '후기 작성일';
COMMENT ON COLUMN REVIEW.REVIEW_DEL_FL IS '후기 삭제 여부 ( Y / N )';
COMMENT ON COLUMN REVIEW.MEMBER_NO IS '예약한 회원 번호(FK)';
COMMENT ON COLUMN REVIEW.STORE_NO IS '사업자 등록 번호 (FK)';


-- REVIEW_HASH definition

CREATE TABLE "REVIEW_HASH" 
   (	"REVIEW_NO" NUMBER NOT NULL ENABLE, 
	"HASH_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_REVIEW_HASH" PRIMARY KEY ("REVIEW_NO", "HASH_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "REVIEW_HASH" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_HASH_1" FOREIGN KEY ("REVIEW_NO")
	  REFERENCES "REVIEW" ("REVIEW_NO") ENABLE;
  ALTER TABLE "REVIEW_HASH" ADD CONSTRAINT "FK_HASH_TO_REVIEW_HASH_1" FOREIGN KEY ("HASH_NO")
	  REFERENCES "HASH" ("HASH_NO") ENABLE;

CREATE UNIQUE INDEX "PK_REVIEW_HASH" ON "REVIEW_HASH" ("REVIEW_NO", "HASH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN REVIEW_HASH.REVIEW_NO IS '후기글 번호 (PFK)';
COMMENT ON COLUMN REVIEW_HASH.HASH_NO IS '해시태그 번호 (PFK)';


-- REVIEW_MENU definition

CREATE TABLE "REVIEW_MENU" 
   (	"REVIEW_NO" NUMBER NOT NULL ENABLE, 
	"MENU_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_REVIEW_MENU" PRIMARY KEY ("REVIEW_NO", "MENU_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "REVIEW_MENU" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_MENU_1" FOREIGN KEY ("REVIEW_NO")
	  REFERENCES "REVIEW" ("REVIEW_NO") ENABLE;
  ALTER TABLE "REVIEW_MENU" ADD CONSTRAINT "FK_MENU_TO_REVIEW_MENU_1" FOREIGN KEY ("MENU_NO")
	  REFERENCES "MENU" ("MENU_NO") ENABLE;

CREATE UNIQUE INDEX "PK_REVIEW_MENU" ON "REVIEW_MENU" ("REVIEW_NO", "MENU_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN REVIEW_MENU.REVIEW_NO IS '후기글 번호 (PK)';
COMMENT ON COLUMN REVIEW_MENU.MENU_NO IS '메뉴 번호 (PK)';


-- REVIEW_REPLY definition

CREATE TABLE "REVIEW_REPLY" 
   (	"REPLY_NO" NUMBER NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"REPLY_CONENT" NVARCHAR2(1000) NOT NULL ENABLE, 
	"REPLY_REG_DATE" DATE NOT NULL ENABLE, 
	"REPLY_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"REVIEW_NO" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_REVIEW_REPLY" PRIMARY KEY ("REPLY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "REPLY_DEL_FL_CHECK" CHECK ("REPLY_DEL_FL" IN('Y','N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "REVIEW_REPLY" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_REPLY_1" FOREIGN KEY ("REVIEW_NO")
	  REFERENCES "REVIEW" ("REVIEW_NO") ENABLE;

CREATE UNIQUE INDEX "PK_REVIEW_REPLY" ON "REVIEW_REPLY" ("REPLY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN REVIEW_REPLY.REPLY_NO IS '사장님 댓글 번호 (PK)';
COMMENT ON COLUMN REVIEW_REPLY.STORE_NO IS '사업자 등록 번호';
COMMENT ON COLUMN REVIEW_REPLY.REPLY_CONENT IS '댓글 내용';
COMMENT ON COLUMN REVIEW_REPLY.REPLY_REG_DATE IS '댓글 작성일';
COMMENT ON COLUMN REVIEW_REPLY.REPLY_DEL_FL IS '댓글 삭제 여부 ( Y /  N)';
COMMENT ON COLUMN REVIEW_REPLY.REVIEW_NO IS '후기글 번호 (PK)';


-- UPLOAD_IMAGE definition

CREATE TABLE "UPLOAD_IMAGE" 
   (	"IMAGE_NO" NUMBER NOT NULL ENABLE, 
	"IMAGE_PATH" VARCHAR2(500) NOT NULL ENABLE, 
	"IMG_RENAME" VARCHAR2(100) NOT NULL ENABLE, 
	"IMG_UPLOAD_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"IMAGE_ORDER" NUMBER NOT NULL ENABLE, 
	"STORE_NO" NVARCHAR2(30) NOT NULL ENABLE, 
	"REVIEW_NO" NUMBER NOT NULL ENABLE, 
	"IMG_ORIGINAL_NAME" NVARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_UPLOAD_IMAGE" PRIMARY KEY ("IMAGE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "UPLOAD_IMAGE" ADD CONSTRAINT "FK_STORE_TO_UPLOAD_IMAGE_1" FOREIGN KEY ("STORE_NO")
	  REFERENCES "STORE" ("STORE_NO") ENABLE;
  ALTER TABLE "UPLOAD_IMAGE" ADD CONSTRAINT "FK_REVIEW_TO_UPLOAD_IMAGE_1" FOREIGN KEY ("REVIEW_NO")
	  REFERENCES "REVIEW" ("REVIEW_NO") ENABLE;

CREATE UNIQUE INDEX "PK_UPLOAD_IMAGE" ON "UPLOAD_IMAGE" ("IMAGE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN UPLOAD_IMAGE.IMAGE_NO IS '이미지 번호 (PK)';
COMMENT ON COLUMN UPLOAD_IMAGE.IMAGE_PATH IS '이미지 경로';
COMMENT ON COLUMN UPLOAD_IMAGE.IMG_RENAME IS '이미지 변경명';
COMMENT ON COLUMN UPLOAD_IMAGE.IMG_UPLOAD_DATE IS '이미지 업로드 날짜';
COMMENT ON COLUMN UPLOAD_IMAGE.IMAGE_ORDER IS '이미지 순서';
COMMENT ON COLUMN UPLOAD_IMAGE.STORE_NO IS '사업자 등록 번호 (FK)';
COMMENT ON COLUMN UPLOAD_IMAGE.REVIEW_NO IS '후기글 번호 (FK)';


-- REPORT definition

CREATE TABLE "REPORT" 
   (	"REPORT_NO" NUMBER NOT NULL ENABLE, 
	"REPORT_CONTENT" NVARCHAR2(1000) NOT NULL ENABLE, 
	"REVIEW_NO" NUMBER NOT NULL ENABLE, 
	"MEMBER_NO" NUMBER NOT NULL ENABLE, 
	"REPORT_DATE" DATE DEFAULT SYSDATE, 
	"REPORT_DEL_FL" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	"REPORTER_NAME" NVARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT "PK_REPORT" PRIMARY KEY ("REPORT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_REVIEW_TO_REPORT_1" FOREIGN KEY ("REVIEW_NO")
	  REFERENCES "REVIEW" ("REVIEW_NO") ENABLE;
  ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY ("MEMBER_NO")
	  REFERENCES "MEMBER" ("MEMBER_NO") ENABLE;

CREATE UNIQUE INDEX "PK_REPORT" ON "REPORT" ("REPORT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN REPORT.REPORT_NO IS '댓글 신고 번호 (PK)';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고 내용';
COMMENT ON COLUMN REPORT.REVIEW_NO IS '후기글 번호 (FK)';
COMMENT ON COLUMN REPORT.MEMBER_NO IS '회원 번호(PK)';