INSERT INTO BOARD_TYPE (BOARD_CODE,BOARD_NAME) VALUES (1,'국내');
INSERT INTO BOARD_TYPE (BOARD_CODE,BOARD_NAME) VALUES (2,'국외');
INSERT INTO BOARD_TYPE (BOARD_CODE,BOARD_NAME) VALUES (3,'자유');
INSERT INTO BOARD_TYPE (BOARD_CODE,BOARD_NAME) VALUES (4,'공지');
